# Site settings
title: Felix
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile

sections:
  - news
  - arts
  - sports
highlights:
  - long-read
  - comment
  - something-else

prose_form: &prose_form
  - name: "layout"
    field:
      element: "hidden"
      value: "post"
  - name: "title"
    field:
      element: "text"
      placeholder: "Article Title"
  - name: "subtitle"
    field:
      label: "Subtitle"
      element: "text"
      help: "The subtitle is like a title but more sub"
      placeholder: "Subtitle"
  - name: "published"
    field:
      label: "Published"
      element: "checkbox"
      value: false
  - name: "headline"
    field:
      label: "Headline Article"
      help: "Show the article on the homepage. Only the N most recent headline articles are shown on the homepage"
      element: "checkbox"
      value: false
  - name: "featured"
    field:
      label: "Section Featured"
      help: "Show the article in the section block on the homepage. Only the N most recent featured articles are shown on the homepage"
      element: "checkbox"
      value: false
  - name: "highlight"
    field:
      element: "select"
      label: "Highlight"
      placeholder: "(optional) Choose highlight"
      help: "Highlight the article as special for listing at the bottom of the page"
      options:
        - name: "Long read"
          value: "long-read"
        - name: "Comment"
          value: "comment"
        - name: "Some Section"
          value: "something-else"
  - name: "category"
    field:
      element: "select"
      label: "Section"
      placeholder: "Choose Section"
      help: "Choose a section from the list. (category)"
      options:
        - name: "Arts"
          value: "arts"
        - name: "News"
          value: "news"
        - name: "Culture"
          value: "culture"
        - name: "Sport"
          value: "sport"
  - name: "tags"
    field:
      element: "multiselect"
      label: "Tags"
      placeholder: "Choose Tags"
      alterable: true
      help: "Choose from a list of tags or add a new one below"
      options:
        - name: "donald-trump"
        - name: "us-election"

prose:
  siteurl: "https://felixonline.github.io"
  ignore:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - _config.yml
    - _layouts
  metadata:
    _posts:
      *prose_form
