baseURL: https://felixonline.github.io/v2/
disablePathToLower: true
languageCode: en-us
title: Felix
theme: felix
canonifyurls: false

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  highlight: "highlights"
  publication: "publications"

# ignoreFiles:
#   - data

params:
  imageProxy: "//images.weserv.nl/?url="
  displayCategories:
    - arts
    - books
    - comment
    - film
    - food
    - games
    - music
    - news
    - science
    - sport
    - tech
    - travel
    - tv
