baseURL: https://felixonline.github.io/v2/
disablePathToLower: true
languageCode: en-us
title: Felix
theme: felix
canonifyurls: false

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  highlight: "highlights"
  publication: "publications"

# ignoreFiles:
#   - data

params:
  imageProxy: "//images.weserv.nl/?url="
  displayCategories:
    - news
    - comment
    - science
    - arts
    - film
    - tv
    - music
    - games
    - tech
    - food
    - travel
    - sport
    # - books # we don't really have enough content for this section at the moment
