baseURL: https://felixonline.github.io/v2/
disablePathToLower: true
languageCode: en-us
title: Felix
theme: felix
canonifyurls: false

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  highlight: "highlights"
  publication: "publications"

# ignoreFiles:
#   - data

params:
  imageProxy: "//images.weserv.nl/?url="
  description: Felix Online is the online companion to Felix, the student newspaper of Imperial College London.
  displayCategories:
    - name: news
      colour: "cd1619"
      tags:
        - on-campus
        - higher-education
        - wider-world
        - imported
        - image
    - name: comment
      colour: "00a7d3"
      tags:
        - politics
        - world-affairs
        - personal
        - health-&-mental-health
        - on-campus
        - imported
        - image
    - name: science
      colour: "005722"
      tags:
        - engineering
        - natural-science
        - medicine
        - interviews
        - imported
        - image
    - name: arts
      colour: "54166b"
      tags:
        - review
        - comment
        - feature
        - theatre
        - visual-art
        - opera-&-ballet
        - imported
        - image
    - name: film
      colour: "7a0040"
      tags:
        - review
        - feature
        - opinion
        - festivals
        - imported
        - image
    - name: tv
      display: TV
      colour: "007e50"
      tags:
        - review
        - feature
        - opinion
        - imported
        - image
    - name: music
      colour: "0051a0"
      tags:
        - review
        - feature
        - demo-dump
        - opinion
        - imported
        - image
    - name: games
      colour: "00546c"
      tags:
        - review
        - feature
        - opinion
        - imported
        - image
    - name: food
      colour: "e5c700"
      tags:
        - out-&-about
        - recipe
        - feature
        - imported
        - image
    - name: travel
      colour: "000000"
      tags:
        - imported
        - image
    - name: sport
      colour: "159632"
      tags:
        - match-report
        - tours
        - imported
        - image
    # - books # we don't really have enough content for this section at the moment
