baseURL: https://charlieegan3.github.io/felixonline/
disablePathToLower: true
languageCode: en-us
title: Felix
theme: felix
canonifyurls: false

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  highlight: "highlights"

ignoreFiles:
  - data

params:
  imageProxy: "//images.weserv.nl/?url="
