baseURL: https://felixonline.github.io/v2/
disablePathToLower: true
languageCode: en-us
title: Felix
theme: felix
canonifyurls: false

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
  highlight: "highlights"
  publication: "publications"

# ignoreFiles:
#   - data

params:
  imageProxy: "//images.weserv.nl/?url="
  displayCategories:
    - name: news
      tags:
        - foo
        - bar
    - name: comment
      tags:
        - foo
        - bar
    - name: science
      tags:
        - foo
        - bar
    - name: arts
      tags:
        - foo
        - bar
    - name: film
      tags:
        - foo
        - bar
    - name: tv
      display: TV
      tags:
        - foo
        - bar
    - name: music
      tags:
        - foo
        - bar
    - name: games
      tags:
        - foo
        - bar
    - name: tech
      tags:
        - foo
        - bar
    - name: food
      tags:
        - foo
        - bar
    - name: travel
      tags:
        - foo
        - bar
    - name: sport
      tags:
        - foo
        - bar
    # - books # we don't really have enough content for this section at the moment
